= Project: Duck Arduino Reciever

This is the sketch that holds the code itilized in making the duck respond to the actions sent from the Arduino transmitter. This reciever is able to control the turn of the rudder and which motors are being used. 

== Step 1: Installation

1. Upload the sketch to your Arduino
2. Edit it to fit the specifications of your design
3. Let your duck go wild!

== Step 2: Assemble the circuit

Assemble the circuit following the schematic layout.png attached in this folder 

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact maureensanchez99 https://id.arduino.cc/maureensanchez99

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
|    | Arduino Uno    | 1234-abcd   | 1
|    | Red LED        | 2345-asdf   | 5
|    | Arduino Zero   | ABX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
